var products = [
    {
        id: 1,
        name: "Whitening Roll-On - 72hr - Powder Soft",
        desc: "Long-lasting odor protection and skin brightening.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 2,
        name: "Whitening Roll-On - 48hr - Instant White",
        desc: "Provides immediate brightening and 48hr protection.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 3,
        name: "Whitening Roll-On - 48hr - Elder Rose",
        desc: "Delicate floral scent with skin-toning benefits.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 4,
        name: "Whitening Roll-On - 48hr - Hair Delaying",
        desc: "Helps reduce hair growth while brightening skin.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 5,
        name: "Whitening Roll-On - 48hr - Cotton Candy",
        desc: "Sweet-scented protection for smooth underarms.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 6,
        name: "Radiant Bright Underarm Serum - Cucumber & Green Tea",
        desc: "Concentrated serum for refreshing underarm care.",
        price: 21.0,
        discount: 30,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 7,
        name: "Radiant Bright Underarm Serum - Silky Touch",
        desc: "Fast-absorbing formula for a smooth, velvety finish.",
        price: 21.0,
        discount: 30,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 8,
        name: "Radiant Bright Underarm Serum - Jouri Rose",
        desc: "Nourishing serum with the essence of Jouri rose.",
        price: 21.0,
        discount: 30,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 9,
        name: "Radiant Bright Underarm Serum - Powder Soft",
        desc: "Brightens and softens skin with a light powder finish.",
        price: 21.0,
        discount: 30,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 10,
        name: "Radiant Bright Underarm Serum - Delays Shaving",
        desc: "Inhibits hair regrowth and evens skin tone.",
        price: 21.0,
        discount: 30,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 11,
        name: "Radiant Bright Underarm Serum - Fragrance Free",
        desc: "Gentle brightening serum for sensitive skin.",
        price: 21.0,
        discount: 30,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 12,
        name: "Radiant Bright Underarm Serum - Instant Bright",
        desc: "Visible brightening results for dull underarms.",
        price: 21.0,
        discount: 30,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 13,
        name: "Whitening Roll-On - 48hr - Arabian Oud",
        desc: "Luxury scent combined with 48-hour protection.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 14,
        name: "4in1 Whitening Cleanser",
        desc: "Cleanses, exfoliates, masks, and brightens.",
        price: 12.0,
        discount: 0,
        image: null,
        category: "face",
        tag: ["radiance", "texture"],
    },
    {
        id: 15,
        name: "Whitening Roll-On - 48hr - Fragrance Free",
        desc: "Odor protection for highly sensitive skin.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 16,
        name: "Whitening Roll-On - 48hr - Pacific Islands",
        desc: "Tropical scent with effective skin brightening.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 17,
        name: "Whitening Roll-On - 48hr - Invisible Touch",
        desc: "Stain-free protection that leaves no white marks.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 18,
        name: "Everyone Barrier Cream",
        desc: "Daily protection for all skin types.",
        price: 17.9,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture", "texture"],
    },
    {
        id: 19,
        name: "Whitening Roll-On - 48hr - Beauty Pearl",
        desc: "Infused with pearl extracts for luminous skin.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 20,
        name: "Whitening Roll-On - 48hr - Instant White",
        desc: "Immediate brightening for the underarm area.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 21,
        name: "Sebum-Control Balancing Serum",
        desc: "Regulates oil production and minimizes pores.",
        price: 19.0,
        discount: 0,
        image: null,
        category: "face",
        tag: ["oiliness", "acne", "pore"],
    },
    {
        id: 22,
        name: "4in1 Cleanser (Radiance)",
        desc: "Multi-functional face wash for glowing skin.",
        price: 10.3,
        discount: 0,
        image: null,
        category: "face",
        tag: ["radiance", "texture"],
    },
    {
        id: 23,
        name: "Unifying Brightening Serum",
        desc: "Evens out skin tone and fades dark spots.",
        price: 21.0,
        discount: 0,
        image: null,
        category: "face",
        tag: ["spots", "radiance"],
    },
    {
        id: 24,
        name: "Instant Bright Glow Serum",
        desc: "Provides a healthy, luminous glow instantly.",
        price: 17.5,
        discount: 0,
        image: null,
        category: "face",
        tag: ["radiance"],
    },
    {
        id: 25,
        name: "Anti-Wrinkle & Radiance Serum",
        desc: "Fights aging signs while enhancing skin light.",
        price: 21.0,
        discount: 0,
        image: null,
        category: "face",
        tag: ["wrinkles", "radiance"],
    },
    {
        id: 26,
        name: "Super Hydrating Serum",
        desc: "Deep moisture boost for dehydrated skin.",
        price: 21.0,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture"],
    },
    {
        id: 27,
        name: "Whitening Intimate Wash",
        desc: "Gentle cleanser for sensitive areas.",
        price: 8.6,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture", "radiance"],
    },
    {
        id: 28,
        name: "Age Defense Fluid SPF50+",
        desc: "Sun protection with anti-aging benefits.",
        price: 12.2,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture", "spots"],
    },
    {
        id: 29,
        name: "Micellar Water - Rose",
        desc: "Gently removes makeup and impurities.",
        price: 3.7,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture", "pore"],
    },
    {
        id: 30,
        name: "Future Barrier Cream",
        desc: "Advanced restoration for the skin barrier.",
        price: 25.9,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture", "texture"],
    },
    {
        id: 31,
        name: "Feet & Heels Repair Cream",
        desc: "Softens dry, cracked skin on feet.",
        price: 3.9,
        discount: 0,
        image: null,
        category: "body",
        tag: ["texture"],
    },
    {
        id: 32,
        name: "Honey Moisturizing Soap",
        desc: "Fragrance-free cleansing with honey.",
        price: 2.9,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture"],
    },
    {
        id: 33,
        name: "Beeswax Ointment",
        desc: "Versatile balm for dry skin patches.",
        price: 4.2,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture"],
    },
    {
        id: 34,
        name: "Lip Care - Shea & Avocado",
        desc: "Nourishing lip balm with natural oils.",
        price: 2.9,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture"],
    },
    {
        id: 35,
        name: "Lip Care - Rose",
        desc: "Protects lips with a subtle floral essence.",
        price: 2.9,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture"],
    },
    {
        id: 36,
        name: "Lip Care - Cherry",
        desc: "Sweet cherry flavor with deep hydration.",
        price: 2.9,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture"],
    },
    {
        id: 37,
        name: "Lip Care - Flavor Free",
        desc: "Essential protection without added scents.",
        price: 2.9,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture"],
    },
    {
        id: 38,
        name: "Lip Care - Ultrascreen SPF30",
        desc: "UV protection for delicate lips.",
        price: 2.9,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture"],
    },
    {
        id: 39,
        name: "Carrot Suntan Oil",
        desc: "Promotes a deep, natural tan.",
        price: 7.4,
        discount: 0,
        image: null,
        category: "body",
        tag: ["radiance"],
    },
    {
        id: 40,
        name: "Shower Cream - Lavender 750ml",
        desc: "Relaxing body wash in a large size.",
        price: 4.2,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 41,
        name: "Shower Cream - Watermelon 750ml",
        desc: "Refreshing fruity cleanse for the body.",
        price: 4.2,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 42,
        name: "Shower Cream - Papaya 750ml",
        desc: "Smoothing shower cream with papaya.",
        price: 4.2,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 43,
        name: "Shower Cream - Ananas 750ml",
        desc: "Energizing pineapple-scented body wash.",
        price: 4.2,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 44,
        name: "Shower Cream - Coco-Vanilla 750ml",
        desc: "Warm and tropical scent for daily use.",
        price: 4.2,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 45,
        name: "Shower Cream - Lavender",
        desc: "Soothing lavender-infused body wash.",
        price: 2.9,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 46,
        name: "Shower Cream - Ananas",
        desc: "Refreshing pineapple cleansing formula.",
        price: 2.9,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 47,
        name: "Shower Cream - Papaya",
        desc: "Gently exfoliates while you wash.",
        price: 2.9,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 48,
        name: "Shower Cream - Watermelon",
        desc: "Vibrant watermelon scent for fresh skin.",
        price: 2.9,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 49,
        name: "Shower Cream - Lemon Mint",
        desc: "Cooling and invigorating body wash.",
        price: 2.9,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 50,
        name: "Shower Cream - Pine",
        desc: "Fresh forest scent for a crisp clean.",
        price: 2.9,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 51,
        name: "Shower Cream - Coco-Vanilla",
        desc: "Moisturizing shower cream with a tropical scent.",
        price: 2.88,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 52,
        name: "Whitening Sensitive Zone Soap",
        desc: "Natural soap that lightens and rejuvenates sensitive areas.",
        price: 4.8,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 53,
        name: "Hygienic Wash",
        desc: "pH-balanced intimate wash for daily freshness.",
        price: 8.0,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 54,
        name: "Instant Bright Day Cream",
        desc: "Brightens and evens skin tone for a radiant daytime look.",
        price: 15.15,
        discount: 0,
        image: null,
        category: "face",
        tag: ["radiance", "moisture", "spots"],
    },
    {
        id: 55,
        name: "Instant Bright Eye Cream",
        desc: "Reduces dark circles and puffiness while brightening eyes.",
        price: 15.15,
        discount: 0,
        image: null,
        category: "face",
        tag: ["dark-circles", "radiance", "eye-bag"],
    },
    {
        id: 56,
        name: "Instant Bright Toner",
        desc: "Clarifies the complexion and refines skin texture.",
        price: 11.64,
        discount: 0,
        image: null,
        category: "face",
        tag: ["pore", "radiance", "texture"],
    },
    {
        id: 57,
        name: "Instant Bright Micellar Water",
        desc: "3-in-1 cleanser that removes makeup and brightens skin.",
        price: 9.32,
        discount: 0,
        image: null,
        category: "face",
        tag: ["radiance", "moisture"],
    },
    {
        id: 58,
        name: "Fortifying Shampoo 400ml",
        desc: "Strengthens hair from root to tip to prevent hair fall.",
        price: 2.61,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["hair-loss", "breakage"],
    },
    {
        id: 59,
        name: "Keratin Conditioner",
        desc: "Smooths hair fibers and provides deep repair.",
        price: 1.73,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["breakage", "frizz"],
    },
    {
        id: 60,
        name: "Keratin Shampoo 400ml",
        desc: "Restores hair vitality and smooths unruly strands.",
        price: 2.61,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["breakage", "frizz"],
    },
    {
        id: 61,
        name: "Keratin Oil Replacement",
        desc: "Leave-in treatment for intense repair and heat protection.",
        price: 3.07,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["breakage", "heat", "frizz"],
    },
    {
        id: 62,
        name: "Nourishing Conditioner",
        desc: "Deeply hydrates and detangles dry, damaged hair.",
        price: 1.73,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["dry-hair", "moisture"],
    },
    {
        id: 63,
        name: "Nourishing Shampoo 400ml",
        desc: "Gentle cleansing for intense hydration and softness.",
        price: 2.61,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["dry-hair", "moisture"],
    },
    {
        id: 64,
        name: "Dandruff Shampoo 400ml",
        desc: "Eliminates dandruff and soothes itchy scalps.",
        price: 2.61,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["dandruff", "oily-scalp"],
    },
    {
        id: 65,
        name: "Dandruff Conditioner",
        desc: "Soothes the scalp while keeping hair soft and flake-free.",
        price: 1.73,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["dandruff"],
    },
    {
        id: 66,
        name: "Age Defense Fluid SPF50+ - Tinted - Light",
        desc: "High sun protection with a light tint and anti-aging benefits.",
        price: 12.21,
        discount: 0,
        image: null,
        category: "face",
        tag: ["wrinkles", "radiance"],
    },
    {
        id: 67,
        name: "Age Defense Fluid SPF50+ - Tinted - Medium",
        desc: "Anti-aging sun protection with a medium tint for even skin.",
        price: 12.21,
        discount: 0,
        image: null,
        category: "face",
        tag: ["wrinkles", "radiance"],
    },
    {
        id: 68,
        name: "Facial Purifying Soap",
        desc: "Cleanses deeply to remove excess oil and impurities.",
        price: 3.77,
        discount: 0,
        image: null,
        category: "face",
        tag: ["oiliness", "acne", "pore"],
    },
    {
        id: 69,
        name: "Micellar Water - Rose (Small)",
        desc: "Gentle rose-infused cleanser for sensitive skin.",
        price: 1.79,
        discount: 0,
        image: null,
        category: "face",
        tag: ["radiance", "moisture"],
    },
    {
        id: 70,
        name: "Whitening Facial Soap - Papaya",
        desc: "Exfoliates and brightens with natural papaya enzymes.",
        price: 4.0,
        discount: 0,
        image: null,
        category: "face",
        tag: ["texture", "radiance", "spots"],
    },
    {
        id: 71,
        name: "Whitening Eye Cream SPF30",
        desc: "Brightens the eye area while providing UV protection.",
        price: 7.44,
        discount: 0,
        image: null,
        category: "face",
        tag: ["dark-circles", "eye-bag", "radiance"],
    },
    {
        id: 72,
        name: "Whitening Day Cream SPF30",
        desc: "Fades dark spots and protects against sun damage.",
        price: 7.2,
        discount: 0,
        image: null,
        category: "face",
        tag: ["spots", "radiance"],
    },
    {
        id: 73,
        name: "Whitening Toner",
        desc: "Evens out skin tone and removes residual impurities.",
        price: 7.76,
        discount: 0,
        image: null,
        category: "face",
        tag: ["spots", "radiance"],
    },
    {
        id: 74,
        name: "Whitening Makeup Remover",
        desc: "Dissolves makeup and brightens the complexion.",
        price: 8.0,
        discount: 0,
        image: null,
        category: "face",
        tag: ["radiance"],
    },
    {
        id: 75,
        name: "Whitening Lifting Facial Foam",
        desc: "Cleansing foam that firms skin and enhances radiance.",
        price: 5.99,
        discount: 0,
        image: null,
        category: "face",
        tag: ["wrinkles", "radiance"],
    },
    {
        id: 76,
        name: "Whitening Facial Wash",
        desc: "Gentle daily cleanser for a brighter, clearer face.",
        price: 9.15,
        discount: 0,
        image: null,
        category: "face",
        tag: ["radiance", "spots"],
    },
    {
        id: 77,
        name: "Whitening Facial Soap",
        desc: "Classic whitening soap for daily skin brightening.",
        price: 3.77,
        discount: 0,
        image: null,
        category: "face",
        tag: ["radiance"],
    },
    {
        id: 78,
        name: "Night Cream",
        desc: "Overnight recovery cream for a glowing morning look.",
        price: 10.29,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture", "radiance"],
    },
    {
        id: 79,
        name: "Day Cream SPF25 - Dry Skin",
        desc: "Intense hydration and protection for dry skin types.",
        price: 10.29,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture", "radiance"],
    },
    {
        id: 80,
        name: "Propolis Facial Wash",
        desc: "Purifies oily and combination skin to prevent breakouts.",
        price: 9.15,
        discount: 0,
        image: null,
        category: "face",
        tag: ["acne", "oiliness", "pore"],
    },
    {
        id: 81,
        name: "Suntan Oil Gold",
        desc: "Provides a deep tan with a glamorous golden shimmer.",
        price: 10.34,
        discount: 0,
        image: null,
        category: "body",
        tag: ["radiance"],
    },
    {
        id: 82,
        name: "Roll-On - 48hr - Sport Pulse",
        desc: "Long-lasting protection for an active lifestyle.",
        price: 2.7,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 83,
        name: "Roll-On - 48hr - Elder Rose",
        desc: "Fresh floral scent with reliable odor protection.",
        price: 2.7,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 84,
        name: "Roll-On - 48hr - Pacific Islands",
        desc: "Tropical freshness that keeps you dry all day.",
        price: 2.7,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 85,
        name: "Roll-On - 48hr - Invisible Touch",
        desc: "Anti-white mark protection with a gentle feel.",
        price: 2.7,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 86,
        name: "Roll-On - 48hr - Cotton Candy",
        desc: "Sweet-scented 48-hour protection.",
        price: 2.7,
        discount: 0,
        image: null,
        category: "body",
        tag: ["moisture"],
    },
    {
        id: 87,
        name: "Roll-On - 48hr - Beauty Pearl",
        desc: "Enriched with pearl extracts for smooth underarms.",
        price: 2.7,
        discount: 0,
        image: null,
        category: "body",
        tag: ["texture", "moisture"],
    },
    {
        id: 88,
        name: "Whitening Roll-On - 72hr - Jouri Rose",
        desc: "Advanced 72-hour protection that lightens skin.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 89,
        name: "Whitening Roll-On - 24hr - 0% Aluminum",
        desc: "Aluminum-free whitening protection for sensitive skin.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance", "redness"],
    },
    {
        id: 90,
        name: "Men's Whitening Roll-On - 72hr - Ocean Fresh",
        desc: "Powerful protection and skin brightening for men.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 91,
        name: "Whitening Roll-On - 48hr - Hair Delaying",
        desc: "Lightens underarms and slows hair growth.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 92,
        name: "Whitening Roll-On - 48hr - Invisible Touch",
        desc: "Whitening formula that leaves no stains on clothes.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 93,
        name: "Whitening Roll-On - 48hr - Cool Breeze",
        desc: "Cooling sensation with skin-brightening properties.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 94,
        name: "Whitening Roll-On - 48hr - Pacific Islands",
        desc: "Tropical scent with effective skin lightening.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 95,
        name: "Whitening Roll-On - 48hr - Green Forest",
        desc: "Fresh, earthy scent with whitening benefits.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 96,
        name: "Whitening Roll-On - 48hr - Elder Rose",
        desc: "Classic floral brightening protection.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 97,
        name: "Whitening Roll-On - 48hr - Sport Pulse",
        desc: "Whitening deodorant designed for high activity.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 98,
        name: "Whitening Roll-On - 48hr - Indian Bakhour",
        desc: "Exotic fragrance that brightens underarm skin.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 99,
        name: "Whitening Roll-On - 48hr - Arabian Oud",
        desc: "Luxurious oud scent with 48hr whitening power.",
        price: 9.16,
        discount: 0,
        image: null,
        category: "body",
        tag: ["spots", "radiance"],
    },
    {
        id: 100,
        name: "Face Mineral Sunscreen SPF30",
        desc: "Natural mineral protection for safe sun exposure.",
        price: 14.0,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture"],
    },
    {
        id: 101,
        name: "Ultrascreen Invisible SPF50",
        desc: "SPF 50 hybrid sunscreen with UVA, UVB, and IR protection.",
        price: 14.0,
        discount: 0,
        image: null,
        category: "face",
        tag: ["moisture"],
    },
    {
        id: 102,
        name: "Clear Skin Kit",
        desc: "A simple 3-step routine to cleanse, treat, and hydrate acne-prone skin without over-drying.",
        price: 25.0,
        discount: 0,
        image: null,
        category: "bundle",
        tag: ["acne", "oiliness", "pore", "texture"],
    },
    {
        id: 103,
        name: "Glow Routine",
        desc: "For brighter, more radiant skin.",
        price: 25.0,
        discount: 20,
        image: null,
        category: "bundle",
        tag: ["droopy upper eyelid", "droopy lower eyelid", "eye-bag", "dark-circles"],
    },
    {
        id: 104,
        name: "Hydration Essentials",
        desc: "Daily hydration for your skin.",
        price: 25.0,
        discount: 15,
        image: null,
        category: "bundle",
        tag: ["oiliness", "acne"],
    },
    {
        id: 105,
        name: "Hair Repair Kit",
        desc: "Repairs and nourishes damaged hair.",
        price: 25.0,
        discount: 0,
        image: null,
        category: "bundle",
        tag: ["acne", "texture"],
    },
    {
        id: 106,
        name: "Beech Glow Set",
        desc: "Your must-haves for summer.",
        price: 25.0,
        discount: 0,
        image: null,
        category: "bundle",
        tag: ["pore", "texture"],
    },
    {
        id: 107,
        name: "His Daily Kit",
        desc: "Fresh and clean daily care.",
        price: 25.0,
        discount: 0,
        image: null,
        category: "bundle",
        tag: ["texture"],
    },
];

const imageFiles = [
    "whitening_roll_on_deo_super_dry_powder_soft_1_plus_1_for_free.webp",
    "whitening_roll_on_deo_instant_white_vitamin_c_1_plus_1_free.webp",
    "whitening_roll_on_deodorant_elder_rose_1_plus_1_free.webp",
    "whitening_roll_on_deodorant_hair_delaying_1_plus_1_free.webp",
    "whitening_roll_on_deodorant_cotton_candy_1_plus_1_free.webp",
    "radiant_bright_underarm_serum_cucumber_and_green_tea_1_plus_1_1.jpg",
    "radiant_bright_underarm_serum_silky_touch_1_plus_1_1.jpg",
    "radiant_bright_underarm_serum_jouri_rose_1_plus_1_1.jpg",
    "radiant_bright_underarm_serum_powder_soft_1_plus_1_1.jpg",
    "radiant_bright_underarm_serum_delays_shaving_1_plus_1.jpg",
    "radiant_bright_underarm_serum_fragrance_free_1_plus_1.jpg",
    "radiant_bright_underarm_serum_instant_bright_1_plus_1.jpg",
    "whitening_roll_on_deodorant_arabian_oud_1_plus_1_free.webp",
    "4_in_1_whitening_cleanser_1_1.webp",
    "whitening_roll-on_deodorant_fragrance_free_1_1.webp",
    "whitening_roll_on_deodorant_pacific_islands_1_plus_1_free.webp",
    "whitening_roll_on_deodorant_invisible_touch_offer_1_plus_1_free.webp",
    "everyone_barrier_cream_10.webp",
    "whitening_roll_on_deodorant_beauty_pearl_1_plus_1_free.webp",
    "whitening_roll_on_deo_instant_white_vitamin_c_9.webp",
    "sebum_control_balancing_1_1.webp",
    "4in1_whitening_cleanser_6.webp",
    "unifying_brightening_1_1.webp",
    "instant_bright_glow_serum_1.webp",
    "anti_wrinkle_and_radiance_1_1.webp",
    "super_hydrating_1_1.webp",
    "whitening_intimate_wash.webp",
    "age_defense_facial_fluid_sunscreen_spf50_.webp",
    "3in1_micellar_cleansing_water_rose_400ml_1.webp",
    "future_barrier_cream_10.webp",
    "feet_and_heels_repair_cream_1.webp",
    "honey_moisturizing_soap_2.webp",
    "beeswax_ointment_fragrance_free_7.webp",
    "lip_care_shea_butter_and_avocado_oil.webp",
    "lip_care_soothing_jouri_rose.webp",
    "lip_care_shimmery_cherry.webp",
    "lip_care_flavor_free.webp",
    "lip_care_ultrascreen_spf30.webp",
    "_5_2_5281018951347_3.webp",
    "lavender_shower_cream_750ml_6.webp",
    "watermelon_shower_cream_750ml_3.webp",
    "exotic_papaya_shower_cream_750ml_6.webp",
    "cool_ananas_shower_cream_750ml_6.webp",
    "coco_vanilla_shower_cream_750ml_6.webp",
    "lavender_shower_cream_5.webp",
    "cool_ananas_shower_cream_5.webp",
    "exotic_papaya_shower_cream_5.webp",
    "watermelon_shower_cream_2.webp",
    "lemon_and_mint_shower_cream_3.webp",
    "fresh_pine_shower_cream_5.webp",
    "coco_vanilla_shower_cream_5.webp",
    "whitening_sensitive_zone_soap.webp",
    "feminine_hygienic_wash_2.webp",
    "instant_bright_day_cream_1.webp",
    "instant_bright_eye_cream_1.webp",
    "instant_bright_facial_toner_1.webp",
    "instant_bright_micellar_water_1.webp",
    "fortifying_shampoo_2.webp",
    "_5_2_5281018092897_1.webp",
    "keratin_shampoo_2.webp",
    "keratin_oil_replacement_2.webp",
    "nourishing_conditioner.webp",
    "nourishing_shampoo.webp",
    "dandruff_relief_shampoo_2.webp",
    "dandruff_relief_conditioner_2.webp",
    "age_defense_tinted_facial_fluid_sunscreen_spf50_light.webp",
    "age_defense_tinted_facial_fluid_sunscreen_spf50_medium_1.webp",
    "facial_purifying_soap_5.webp",
    "3in1_micellar_cleansing_water_rose_100ml_7.webp",
    "whitening_facial_soap_papaya_3.webp",
    "whitening_eye_contour_cream_spf_30_3.webp",
    "whitening_day_cream_spf_30_3.webp",
    "whitening_facial_toner_3.webp",
    "lip_and_eye_whitening_makeup_remover_3.webp",
    "whitening_and_lifting_facial_foam_6.webp",
    "whitening_facial_wash_1.webp",
    "whitening_facial_soap_3.webp",
    "night_complex_cream_3.webp",
    "nourishing_facial_day_cream_spf_25__dry_to_normal_4.webp",
    "propolis_facial_wash_13.webp",
    "suntan_oil_gold.webp",
    "natural_roll_on_deo_sport_pulse_3.webp",
    "natural_roll_on_deo_elder_rose_3.webp",
    "natural_roll_on_deo_pacific_islands_3.webp",
    "natural_roll_on_deo_invisible_touch_3.webp",
    "natural_roll_on_deo_cotton_candy_3.webp",
    "natural_roll_on_deo_beauty_pearl_3.webp",
    "whitening_roll_on_deo_super_dry_jouri_rose_3.webp",
    "whitening_roll_on_deo_zero_aluminum_fragrance_free_4.webp",
    "whitening_roll_on_deo_super_dry_silver_power_ocean_fresh_3.webp",
    "whitening_roll_on_deodorant_hair_delaying_3.webp",
    "whitening_roll_on_deodorant_invisible_touch_3.webp",
    "whitening_roll_on_deodorant_cool_breeze_3.webp",
    "whitening_roll_on_deodorant_pacific_islands_3.webp",
    "whitening_roll_on_deodorant_green_forest_3.webp",
    "whitening_roll_on_deodorant_elder_rose_3.webp",
    "whitening_roll_on_deodorant_sport_pulse_3.webp",
    "whitening_roll_on_deodorant_indian_bakhour_9.webp",
    "whitening_roll_on_deodorant_arabian_oud_3.webp",
    "face_mineral_sunscreen_spf30.jpg",
    "ultrascreen_cream_invisible_sunfilter_spf50_2.webp",
    "acne_solution_set.png",
    "glow_bundle.png",
    "cream_bundle.png",
    "hair_repair_kit.png",
    "beech_glow_set.png",
    "his_daily_kit.png",
];

// auto-assign
products.forEach((product, index) => {
    product.image = imageFiles[index];
});

if (typeof window !== "undefined") {
    window.products = products;
}
