// const products = [
//     {
//         id: 1,
//         name: "Clear Skin Kit",
//         desc: "A simple 3-step routine to cleanse, treat, and hydrate acne-prone skin without over-drying.",
//         price: 25.0,
//         discount: 0,
//         image: "acne_solution_set.png",
//         category: "bundle",
//         tag: ["acne", "oiliness", "pore", "texture"],
//     },
//     {
//         id: 2,
//         name: "Glow Routine",
//         desc: "For brighter, more radiant skin.",
//         price: 25.0,
//         discount: 20,
//         image: "glow_bundle.png",
//         category: "bundle",
//         tag: ["droopy upper eyelid", "droopy lower eyelid", "eye-bag", "dark-circles"],
//     },
//     {
//         id: 3,
//         name: "Hydration Essentials",
//         desc: "Daily hydration for your skin.",
//         price: 25.0,
//         discount: 15,
//         image: "cream_bundle.png",
//         category: "bundle",
//         tag: ["oiliness", "acne"],
//     },
//     {
//         id: 4,
//         name: "Hair Repair Kit",
//         desc: "Repairs and nourishes damaged hair.",
//         price: 25.0,
//         discount: 0,
//         image: "hair_repair_kit.png",
//         category: "bundle",
//         tag: ["acne", "texture"],
//     },
//     {
//         id: 5,
//         name: "Beech Glow Set",
//         desc: "Your must-haves for summer.",
//         price: 25.0,
//         discount: 0,
//         image: "beech_glow_set.png",
//         category: "bundle",
//         tag: ["pore", "texture"],
//     },
//     {
//         id: 6,
//         name: "His Daily Kit",
//         desc: "Fresh and clean daily care.",
//         price: 25.0,
//         discount: 0,
//         image: "his_daily_kit.png",
//         category: "bundle",
//         tag: ["texture"],
//     },
// ];

const products = [
    // --- SKIN CARE: ACNE & OIL CONTROL ---
    {
        id: 1,
        name: "Clear Skin Kit",
        desc: "Complete acne solution.",
        price: 25.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["acne", "oiliness", "pore"],
    },
    {
        id: 2,
        name: "Matte Finish Serum",
        desc: "Controls shine all day.",
        price: 18.0,
        discount: 5,
        image: null,
        category: "skin",
        tag: ["oiliness", "pore"],
    },
    {
        id: 3,
        name: "Blemish Eraser",
        desc: "Spot treatment for breakouts.",
        price: 12.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["acne", "spots"],
    },
    {
        id: 4,
        name: "Pore Refiner Toner",
        desc: "Minimizes large pores.",
        price: 15.0,
        discount: 10,
        image: null,
        category: "skin",
        tag: ["pore", "texture"],
    },
    {
        id: 5,
        name: "Salicylic Deep Wash",
        desc: "Deep cleanses congested skin.",
        price: 20.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["acne", "oiliness"],
    },
    {
        id: 6,
        name: "Oil-Free Moisturizer",
        desc: "Hydration without the grease.",
        price: 22.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["oiliness", "moisture"],
    },
    {
        id: 7,
        name: "Clay Detox Mask",
        desc: "Draws out impurities.",
        price: 19.0,
        discount: 15,
        image: null,
        category: "skin",
        tag: ["oiliness", "pore", "texture"],
    },
    {
        id: 8,
        name: "Post-Acne Scar Gel",
        desc: "Fades marks from old breakouts.",
        price: 24.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["spots", "texture"],
    },
    {
        id: 9,
        name: "Sebum Control Mist",
        desc: "Instant matte refresh.",
        price: 14.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["oiliness"],
    },
    {
        id: 10,
        name: "Blackhead Clearing Scrub",
        desc: "Manual exfoliation for pores.",
        price: 16.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["pore", "acne"],
    },

    // --- SKIN CARE: ANTI-AGING & FIRMNESS ---
    {
        id: 11,
        name: "Retinol Night Repair",
        desc: "Reduces fine lines.",
        price: 45.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["wrinkles", "texture"],
    },
    {
        id: 12,
        name: "Collagen Boost Cream",
        desc: "Improves skin elasticity.",
        price: 50.0,
        discount: 10,
        image: null,
        category: "skin",
        tag: ["firmness", "wrinkles"],
    },
    {
        id: 13,
        name: "Lift & Sculpt Serum",
        desc: "Defines facial contours.",
        price: 55.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["firmness"],
    },
    {
        id: 14,
        name: "Eternal Youth Elixir",
        desc: "Deep cellular renewal.",
        price: 65.0,
        discount: 20,
        image: null,
        category: "skin",
        tag: ["wrinkles", "radiance", "firmness"],
    },
    {
        id: 15,
        name: "Peptide Firming Lotion",
        desc: "Tightens loose skin.",
        price: 42.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["firmness"],
    },
    {
        id: 16,
        name: "Smoothing Night Balm",
        desc: "Wake up with softer lines.",
        price: 38.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["wrinkles", "moisture"],
    },
    {
        id: 17,
        name: "Advanced Filler Gel",
        desc: "Plumps deep-set wrinkles.",
        price: 48.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["wrinkles"],
    },
    {
        id: 18,
        name: "Gravity Defy Cream",
        desc: "Targets sagging jawlines.",
        price: 52.0,
        discount: 5,
        image: null,
        category: "skin",
        tag: ["firmness"],
    },
    {
        id: 19,
        name: "Resurfacing Acid Complex",
        desc: "Chemical exfoliant for aging.",
        price: 35.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["texture", "wrinkles"],
    },
    {
        id: 20,
        name: "Stem Cell Regenerator",
        desc: "High-tech aging support.",
        price: 75.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["firmness", "radiance", "wrinkles"],
    },

    // --- SKIN CARE: RADIANCE & DARK SPOTS ---
    {
        id: 21,
        name: "Vitamin C Glow Serum",
        desc: "Instant brightening.",
        price: 30.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["radiance", "spots"],
    },
    {
        id: 22,
        name: "Dark Spot Corrector",
        desc: "Fades hyperpigmentation.",
        price: 32.0,
        discount: 15,
        image: null,
        category: "skin",
        tag: ["spots"],
    },
    {
        id: 23,
        name: "Brightening Day Fluid",
        desc: "Evens out skin tone.",
        price: 28.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["radiance", "redness"],
    },
    {
        id: 24,
        name: "Illuminating Enzyme Peel",
        desc: "Removes dull surface cells.",
        price: 26.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["radiance", "texture"],
    },
    {
        id: 25,
        name: "Radiance Boost Mask",
        desc: "10-minute glow fix.",
        price: 20.0,
        discount: 10,
        image: null,
        category: "skin",
        tag: ["radiance"],
    },
    {
        id: 26,
        name: "Niacinamide 10% Complex",
        desc: "Targets redness and texture.",
        price: 18.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["redness", "texture", "pore"],
    },
    {
        id: 27,
        name: "Sun Spot Shield",
        desc: "Prevents new UV damage.",
        price: 25.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["spots"],
    },
    {
        id: 28,
        name: "Pearl Bright Concentrate",
        desc: "Luxurious tone evening.",
        price: 40.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["radiance", "spots"],
    },
    {
        id: 29,
        name: "Soothing Anti-Redness Gel",
        desc: "Calms irritated skin.",
        price: 22.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["redness"],
    },
    {
        id: 30,
        name: "Golden Glow Oil",
        desc: "Nourishing radiance.",
        price: 35.0,
        discount: 5,
        image: null,
        category: "skin",
        tag: ["radiance", "moisture"],
    },

    // --- EYE CARE (SPECIFIC TAGS) ---
    {
        id: 31,
        name: "eye-bag Vanisher",
        desc: "Reduces morning puffiness.",
        price: 28.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["eye-bag"],
    },
    {
        id: 32,
        name: "Dark Circle Rescue",
        desc: "Brightens under-eyes.",
        price: 30.0,
        discount: 10,
        image: null,
        category: "skin",
        tag: ["dark-circles"],
    },
    {
        id: 33,
        name: "Upper Lid Lift",
        desc: "Targets sagging upper lids.",
        price: 35.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["droopy upper eyelid", "firmness"],
    },
    {
        id: 34,
        name: "Total Eye Contour",
        desc: "All-in-one eye treatment.",
        price: 42.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["dark-circles", "eye-bag", "wrinkles"],
    },
    {
        id: 35,
        name: "Lower Lid Firmer",
        desc: "Tightens the lower eye area.",
        price: 34.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["droopy lower eyelid", "firmness"],
    },
    {
        id: 36,
        name: "Cooling Eye Roller",
        desc: "Depuffs on the go.",
        price: 15.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["eye-bag"],
    },
    {
        id: 37,
        name: "Retinol Eye Stick",
        desc: "Treats crow's feet.",
        price: 26.0,
        discount: 5,
        image: null,
        category: "skin",
        tag: ["wrinkles", "texture"],
    },
    {
        id: 38,
        name: "Hydrating Eye Patches",
        desc: "Plumps under-eye skin.",
        price: 20.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["moisture", "eye-bag"],
    },
    {
        id: 39,
        name: "Dual Lid Recovery",
        desc: "For both upper and lower lids.",
        price: 48.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["droopy upper eyelid", "droopy lower eyelid"],
    },
    {
        id: 40,
        name: "Bright Eye Concentrate",
        desc: "High-dose caffeine for eyes.",
        price: 29.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["dark-circles"],
    },

    // --- HAIR CARE: SCALP & STRENGTH ---
    {
        id: 41,
        name: "Dandruff Defense",
        desc: "Anti-fungal scalp care.",
        price: 18.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["dandruff"],
    },
    {
        id: 42,
        name: "Anti-Fall Serum",
        desc: "Reduces hair thinning.",
        price: 35.0,
        discount: 10,
        image: null,
        category: "hair",
        tag: ["hair-loss"],
    },
    {
        id: 43,
        name: "Scalp Purifier",
        desc: "Removes oily buildup.",
        price: 20.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["oily-scalp"],
    },
    {
        id: 44,
        name: "Biotin Boost Shampo",
        desc: "Strengthens from the root.",
        price: 22.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["hair-loss", "breakage"],
    },
    {
        id: 45,
        name: "Itch Relief Tonic",
        desc: "Calms irritated scalps.",
        price: 16.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["dandruff"],
    },
    {
        id: 46,
        name: "Keratin Repair Mask",
        desc: "Deep fix for breakage.",
        price: 28.0,
        discount: 5,
        image: null,
        category: "hair",
        tag: ["breakage", "heat"],
    },
    {
        id: 47,
        name: "Volume Root Lift",
        desc: "Adds body to flat hair.",
        price: 19.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["flat"],
    },
    {
        id: 48,
        name: "Follicle Activator",
        desc: "Promotes new hair growth.",
        price: 40.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["hair-loss"],
    },
    {
        id: 49,
        name: "Charcoal Scalp Scrub",
        desc: "Exfoliates for oily roots.",
        price: 24.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["oily-scalp"],
    },
    {
        id: 50,
        name: "Zinc Control Wash",
        desc: "Heavy duty dandruff care.",
        price: 21.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["dandruff"],
    },

    // --- HAIR CARE: MOISTURE & FINISH ---
    {
        id: 51,
        name: "Hydrating Argan Oil",
        desc: "Softens dry ends.",
        price: 25.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["dry-hair"],
    },
    {
        id: 52,
        name: "Frizz-Free Silk",
        desc: "Tames unruly hair.",
        price: 22.0,
        discount: 15,
        image: null,
        category: "hair",
        tag: ["frizz"],
    },
    {
        id: 53,
        name: "Color Preserve Balm",
        desc: "Protects dyed hair.",
        price: 26.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["dyed"],
    },
    {
        id: 54,
        name: "Heat Protection Spray",
        desc: "Prevents styling damage.",
        price: 18.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["heat"],
    },
    {
        id: 55,
        name: "Deep Sea Moisture",
        desc: "Intense hydration mask.",
        price: 30.0,
        discount: 10,
        image: null,
        category: "hair",
        tag: ["dry-hair", "breakage"],
    },
    {
        id: 56,
        name: "Glossing Serum",
        desc: "Mirrors shine for dull hair.",
        price: 24.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["radiance"],
    },
    {
        id: 57,
        name: "Curl Defining Cream",
        desc: "Shape and moisture for curls.",
        price: 23.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["frizz", "dry-hair"],
    },
    {
        id: 58,
        name: "Split End Mender",
        desc: "Temporary fix for damage.",
        price: 21.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["breakage", "dry-hair"],
    },
    {
        id: 59,
        name: "Leave-In Conditioner",
        desc: "Daily detangling moisture.",
        price: 19.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["dry-hair", "frizz"],
    },
    {
        id: 60,
        name: "Bond Repair Treatment",
        desc: "Restores heat-damaged bonds.",
        price: 45.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["heat", "breakage"],
    },

    // --- MEN'S CARE (Specific weights) ---
    {
        id: 61,
        name: "His Charcoal Wash",
        desc: "Deep pore cleaning for men.",
        price: 15.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["oiliness", "pore", "mens"],
    },
    {
        id: 62,
        name: "His Post-Shave Balm",
        desc: "Soothes razor burn.",
        price: 18.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["redness", "moisture", "mens"],
    },
    {
        id: 63,
        name: "His Anti-Fatigue Eye",
        desc: "Targets male dark-circles.",
        price: 25.0,
        discount: 10,
        image: null,
        category: "skin",
        tag: ["dark-circles", "eye-bag", "mens"],
    },
    {
        id: 64,
        name: "His Beard & Face Oil",
        desc: "Nourishes hair and skin.",
        price: 22.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["dry-hair", "moisture", "mens"],
    },
    {
        id: 65,
        name: "His Age-Defense Cream",
        desc: "Fights wrinkles for men.",
        price: 35.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["wrinkles", "firmness", "mens"],
    },
    {
        id: 66,
        name: "His Thickening Shampoo",
        desc: "Volume for thinning hair.",
        price: 20.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["hair-loss", "flat", "mens"],
    },
    {
        id: 67,
        name: "His Scalp Relief",
        desc: "Anti-dandruff for men.",
        price: 18.0,
        discount: 5,
        image: null,
        category: "hair",
        tag: ["dandruff", "mens"],
    },
    {
        id: 68,
        name: "His Daily Kit",
        desc: "Standard 3-step routine.",
        price: 40.0,
        discount: 15,
        image: null,
        category: "bundle",
        tag: ["oiliness", "moisture", "mens"],
    },
    {
        id: 69,
        name: "His Sport Face Wash",
        desc: "Sweat and oil control.",
        price: 14.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["oiliness", "acne", "mens"],
    },
    {
        id: 70,
        name: "His Matte Moisturizer",
        desc: "No-shine hydration.",
        price: 19.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["oiliness", "mens"],
    },

    // --- BUNDLES & SETS ---
    {
        id: 71,
        name: "The Complete Acne Set",
        desc: "Everything for clear skin.",
        price: 60.0,
        discount: 20,
        image: null,
        category: "bundle",
        tag: ["acne", "oiliness", "pore", "texture"],
    },
    {
        id: 72,
        name: "Anti-Aging Power Trio",
        desc: "Retinol, Collagen, Peptides.",
        price: 120.0,
        discount: 25,
        image: null,
        category: "bundle",
        tag: ["wrinkles", "firmness", "texture"],
    },
    {
        id: 73,
        name: "Hydration Station",
        desc: "Serum, Cream, and Mist.",
        price: 50.0,
        discount: 15,
        image: null,
        category: "bundle",
        tag: ["moisture", "dry-hair"],
    },
    {
        id: 74,
        name: "Glow & Go Kit",
        desc: "Vit C and Radiance mask.",
        price: 45.0,
        discount: 10,
        image: null,
        category: "bundle",
        tag: ["radiance", "spots"],
    },
    {
        id: 75,
        name: "Total Scalp Recovery",
        desc: "Scrub and Anti-dandruff wash.",
        price: 38.0,
        discount: 10,
        image: null,
        category: "bundle",
        tag: ["dandruff", "oily-scalp"],
    },
    {
        id: 76,
        name: "The Hair Growth Kit",
        desc: "Serum and Biotin wash.",
        price: 55.0,
        discount: 15,
        image: null,
        category: "bundle",
        tag: ["hair-loss", "breakage"],
    },
    {
        id: 77,
        name: "Sunless Glow Set",
        desc: "Self-tanner and Radiance oil.",
        price: 42.0,
        discount: 0,
        image: null,
        category: "bundle",
        tag: ["radiance"],
    },
    {
        id: 78,
        name: "The Gentleman's Box",
        desc: "Complete mens grooming.",
        price: 70.0,
        discount: 30,
        image: null,
        category: "bundle",
        tag: ["mens", "oiliness", "moisture"],
    },
    {
        id: 79,
        name: "The Eye Specialist",
        desc: "Upper lid, lower lid, circles.",
        price: 85.0,
        discount: 20,
        image: null,
        category: "bundle",
        tag: ["droopy upper eyelid", "droopy lower eyelid", "dark-circles"],
    },
    {
        id: 80,
        name: "Post-Summer Repair",
        desc: "Fixes spots and dryness.",
        price: 55.0,
        discount: 15,
        image: null,
        category: "bundle",
        tag: ["spots", "moisture", "dry-hair"],
    },

    // --- MORE SPECIFIC SKIN TREATMENTS ---
    {
        id: 81,
        name: "Sensitive Skin Balm",
        desc: "Fragrance-free redness care.",
        price: 21.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["redness"],
    },
    {
        id: 82,
        name: "Lactic Acid 5%",
        desc: "Gentle texture smoothing.",
        price: 15.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["texture", "radiance"],
    },
    {
        id: 83,
        name: "Hyaluronic Acid 2%",
        desc: "The ultimate moisture magnet.",
        price: 18.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["moisture"],
    },
    {
        id: 84,
        name: "Azelaic Acid Suspension",
        desc: "Targets redness and acne.",
        price: 19.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["redness", "acne"],
    },
    {
        id: 85,
        name: "Bakuchiol Oil",
        desc: "Plant-based wrinkle repair.",
        price: 30.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["wrinkles", "texture"],
    },
    {
        id: 86,
        name: "Cica Repair Cream",
        desc: "Heals skin barrier.",
        price: 26.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["redness", "moisture"],
    },
    {
        id: 87,
        name: "Zinc & Copper Wash",
        desc: "Antibacterial for oiliness.",
        price: 17.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["oiliness", "acne"],
    },
    {
        id: 88,
        name: "Rosehip Seed Oil",
        desc: "Cold-pressed spots treatment.",
        price: 22.0,
        discount: 5,
        image: null,
        category: "skin",
        tag: ["spots", "moisture"],
    },
    {
        id: 89,
        name: "Eucalyptus Clay Mask",
        desc: "Cooling pore cleaner.",
        price: 18.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["pore", "oiliness"],
    },
    {
        id: 90,
        name: "Probiotic Serum",
        desc: "Balances skin flora.",
        price: 34.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["redness", "texture"],
    },

    // --- FINAL MIXED SELECTION ---
    {
        id: 91,
        name: "Dry Scalp Milk",
        desc: "Hydration for the head.",
        price: 20.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["dry-hair", "dandruff"],
    },
    {
        id: 92,
        name: "Curl Power Jelly",
        desc: "High shine frizz control.",
        price: 18.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["frizz", "radiance"],
    },
    {
        id: 93,
        name: "Silver Toning Wash",
        desc: "Removes brass from dyed hair.",
        price: 24.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["dyed"],
    },
    {
        id: 94,
        name: "Argan Shine Spray",
        desc: "Lightweight hair radiance.",
        price: 16.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["radiance", "dry-hair"],
    },
    {
        id: 95,
        name: "Overnight Hair Rescue",
        desc: "Serum for split ends.",
        price: 32.0,
        discount: 10,
        image: null,
        category: "hair",
        tag: ["breakage", "dry-hair"],
    },
    {
        id: 96,
        name: "Volumizing Powder",
        desc: "Instant lift for flat hair.",
        price: 14.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["flat"],
    },
    {
        id: 97,
        name: "Beard Tamer balm",
        desc: "Softens coarse beard hair.",
        price: 15.0,
        discount: 0,
        image: null,
        category: "hair",
        tag: ["mens", "dry-hair"],
    },
    {
        id: 98,
        name: "Collagen Eye Film",
        desc: "Melts into skin for firmness.",
        price: 40.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["firmness", "wrinkles", "droopy lower eyelid"],
    },
    {
        id: 99,
        name: "Vitamin C Body Lotion",
        desc: "Brightens and hydrates body.",
        price: 28.0,
        discount: 0,
        image: null,
        category: "skin",
        tag: ["radiance", "moisture"],
    },
    {
        id: 100,
        name: "The All-Rounder Kit",
        desc: "One of everything.",
        price: 150.0,
        discount: 40,
        image: null,
        category: "bundle",
        tag: ["acne", "wrinkles", "hair-loss", "dry-hair"],
    },
];
